enableGlobalCache: true

compressionLevel: mixed

enableMirror: true 

checksumBehavior: "throw"

httpTimeout: 300000

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#     spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-4.8.1.cjs

# resolutions:
#   "prismjs": "^1.29.0"
#   "postcss": "^8.4.31"
#   "nth-check": "^2.0.1"
  
# packageExtensions:
#   # Corrections pour les dépendances React courantes
#   "react-scripts@*":
#     dependencies:
#       "web-vitals": "^2.1.4"
#       "webpack": "^5.76.0"
#   "eslint-config-react-app@*":
#     dependencies:
#       "@babel/eslint-parser": "^7.19.1"

# compilerOptions:
#   typescript:
#     enable: true
#     tsconfigPath: "./tsconfig.json"