app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
  feature:
    useAuth: false

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    allowedHeaders: ['Content-Type', 'Authorization']
    # credentials: true

  database:
    # client: better-sqlite3
    # connection: ':memory:'
    client: pg
    connection:
      host: 'localhost'
      port: 5432
      user: postgres
      password: postgres

proxy:
  endpoints:
    '/task/imports':
      target: 'http://localhost:7007'
      changeOrigin: true
