
services:
  db:
    image: postgres:17.0-bookworm
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_ADMIN_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    env_file:
      - .env
    container_name: backend
    build: .
    # build:
    #   context: ./packages/backend
    #   dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_NAME: postgres
    volumes:
      - ./packages/backend:/app/packages/backend
      - /app/node_modules
    restart: always
    ports:
      - "7007:7007"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    # restart: unless-stopped
    # entrypoint: ["/app/entrypoint.sh"]

  # Service pour le frontend (React)
  frontend:
    build: .
    command: yarn workspace app start
    # build:
    #   context: ./packages/app
    #   dockerfile: Dockerfile
    container_name: frontend
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:7007
    volumes:
      - ./packages/app:/app/packages/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always
    # volumes:
    #   - ./packages/app/src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json 
    networks:
      - app-network
    depends_on:
      - db

# Volume pour persister les données de PostgreSQL et pour acceder à pgadmin4
volumes:
  postgres_data:
  pgadmin_data:

# Un réseau Docker personnalisé pour permettre la communication entre les services PostgreSQL et pgAdmin.
networks:
  app-network:
    driver: bridge

